AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  SecretsProvisioner:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 40
      Role: 'arn:aws:iam::730508922179:role/Secrets-Provisioner-Lambda-Role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: SecretsInfo
          SECRETS_PROVISIONER_PATH: /secrets
          SECRETS_SERVICE_ROLE: Secrets-Provisioning-Role
          SECRETS_TAGGING_ROLE: Secrets-Tagging-Role
